#!/bin/bash

# Script para escuchar en el puerto 98 en localhost
# Utiliza netcat (nc) para escuchar en el puerto especificado

PORT=98

# Escuchar en el puerto especificado
echo "Listening on port $PORT..."
nc -l -p $PORT
